import sql from 'mssql';
const fail=(message,status=400)=>Object.assign(Error(message),{status});
export function createWorkforce(config){
 async function run(fn){const p=new sql.ConnectionPool(config);try{await p.connect();return await fn(p)}finally{await p.close()}}
 const manager=u=>['ADMINISTRATOR','PLANNER'].includes(u.role);
 const stock=u=>['ADMINISTRATOR','PLANNER','TECHNICIAN'].includes(u.role);
 return {
 listLoans:u=>run(async p=>(await p.request().input('user',sql.VarChar(24),manager(u)?null:u.id).query(`SELECT L.*,P.PartCode,P.PartName FROM inv.PartLoan L JOIN inv.Part P ON P.PartID=L.PartID WHERE @user IS NULL OR L.UserId=@user ORDER BY CASE WHEN L.Status='BORROWED' THEN 0 ELSE 1 END,L.BorrowedAt DESC`)).recordset),
 async borrow(u,b){if(!stock(u))throw fail('ไม่มีสิทธิ์ยืม',403);if(!Number.isSafeInteger(b.partId)||!Number.isSafeInteger(b.warehouseId)||!Number.isFinite(b.quantity)||b.quantity<=0||b.quantity>1e8||Math.abs(b.quantity*10000-Math.round(b.quantity*10000))>.001)throw fail('จำนวนหรือรหัสไม่ถูกต้อง');return run(async p=>{const t=new sql.Transaction(p);await t.begin(sql.ISOLATION_LEVEL.SERIALIZABLE);try{const r=new sql.Request(t);r.input('part',sql.BigInt,b.partId).input('wh',sql.Int,b.warehouseId).input('qty',sql.Decimal(18,4),b.quantity).input('user',sql.VarChar(24),u.id).input('name',sql.NVarChar(100),u.username).input('remark',sql.NVarChar(1000),String(b.remark||'').slice(0,1000));const v=await r.query(`IF NOT EXISTS(SELECT 1 FROM inv.Part WITH(UPDLOCK,HOLDLOCK) WHERE PartID=@part AND IsActive=1) THROW 50001,'ไม่พบอะไหล่ที่ใช้งาน',1;
 IF COALESCE((SELECT TOP(1) Quantity FROM inv.StockSnapshot WHERE PartID=@part AND WarehouseID=@wh ORDER BY SnapshotDate DESC,StockSnapshotID DESC),0)+COALESCE((SELECT SUM(T.Quantity*TT.QuantitySign) FROM inv.StockTransaction T JOIN ref.InventoryTransactionType TT ON TT.TransactionTypeID=T.TransactionTypeID WHERE T.PartID=@part AND T.WarehouseID=@wh AND ISNULL(T.IsHistorical,0)=0),0)<@qty THROW 50001,'จำนวนคงเหลือไม่พอ',1;
 INSERT inv.PartLoan(PartID,WarehouseID,UserId,Username,Quantity,Remark) VALUES(@part,@wh,@user,@name,@qty,@remark); DECLARE @id bigint=SCOPE_IDENTITY();
 INSERT inv.StockTransaction(TransactionDate,TransactionTypeID,PartID,WarehouseID,Quantity,ReferenceNo,IsHistorical,SourceSystem,DataQualityStatus) SELECT GETDATE(),TransactionTypeID,@part,@wh,@qty,CONCAT('LOAN-',@id),0,'CMMS_LOAN','OK' FROM ref.InventoryTransactionType WHERE TypeCode='BORROW'; SELECT @id LoanID;`);await t.commit();return v.recordset[0]}catch(e){await t.rollback();throw e}})},
 resolveLoan:(u,id,b)=>run(async p=>{if(!['RETURNED','USED'].includes(b.status)||!/^\d+$/.test(id))throw fail('สถานะไม่ถูกต้อง');const t=new sql.Transaction(p);await t.begin();try{const r=new sql.Request(t);r.input('id',sql.BigInt,id).input('user',sql.VarChar(24),u.id).input('manager',sql.Bit,manager(u)).input('name',sql.NVarChar(100),u.username).input('status',sql.VarChar(16),b.status);await r.query(`DECLARE @part bigint,@wh int,@qty decimal(18,4); SELECT @part=PartID,@wh=WarehouseID,@qty=Quantity FROM inv.PartLoan WITH(UPDLOCK,HOLDLOCK) WHERE LoanID=@id AND Status='BORROWED' AND (UserId=@user OR @manager=1); IF @part IS NULL THROW 50001,'รายการปิดแล้วหรือไม่มีสิทธิ์',1;
 INSERT inv.StockTransaction(TransactionDate,TransactionTypeID,PartID,WarehouseID,Quantity,ReferenceNo,IsHistorical,SourceSystem,DataQualityStatus) SELECT GETDATE(),TransactionTypeID,@part,@wh,@qty,CONCAT('LOAN-',@id),0,'CMMS_LOAN','OK' FROM ref.InventoryTransactionType WHERE TypeCode='LOAN_RETURN';
 IF @status='USED' INSERT inv.StockTransaction(TransactionDate,TransactionTypeID,PartID,WarehouseID,Quantity,ReferenceNo,IsHistorical,SourceSystem,DataQualityStatus) SELECT GETDATE(),TransactionTypeID,@part,@wh,@qty,CONCAT('LOAN-',@id),0,'CMMS_LOAN_USED','OK' FROM ref.InventoryTransactionType WHERE TypeCode='ISSUE';
 UPDATE inv.PartLoan SET Status=@status,ResolvedAt=SYSUTCDATETIME(),ResolvedBy=@name WHERE LoanID=@id;`);await t.commit();return {ok:true}}catch(e){await t.rollback();throw e}}),
 overtime:()=>run(async p=>(await p.request().query('SELECT * FROM cmms.TechnicianOvertime ORDER BY WorkDate DESC,OvertimeID DESC')).recordset),
 saveOvertime:(u,b,users)=>run(async p=>{const tech=users.find(x=>x.id===b.userId&&x.role==='TECHNICIAN'&&x.active);if(!tech||!/^\d{4}-\d{2}-\d{2}$/.test(b.workDate)||!Number.isFinite(b.hours)||b.hours<=0||b.hours>24)throw fail('กรุณาเลือก Technician วันที่ และชั่วโมง 0–24');const r=p.request().input('user',sql.VarChar(24),tech.id).input('name',sql.NVarChar(100),tech.displayName).input('date',sql.Date,b.workDate).input('hours',sql.Decimal(5,2),b.hours).input('remark',sql.NVarChar(1000),String(b.remark||'').slice(0,1000)).input('actor',sql.NVarChar(100),u.username);if(b.id){r.input('id',sql.BigInt,b.id).input('version',sql.Int,b.version);const v=await r.query('UPDATE cmms.TechnicianOvertime SET UserId=@user,Username=@name,WorkDate=@date,Hours=@hours,Remark=@remark,UpdatedBy=@actor,UpdatedAt=SYSUTCDATETIME(),Version=Version+1 OUTPUT INSERTED.* WHERE OvertimeID=@id AND Version=@version');if(!v.recordset.length)throw fail('ข้อมูลเปลี่ยนแล้ว กรุณาโหลดใหม่',409);return v.recordset[0]}return(await r.query('INSERT cmms.TechnicianOvertime(UserId,Username,WorkDate,Hours,Remark,UpdatedBy) OUTPUT INSERTED.* VALUES(@user,@name,@date,@hours,@remark,@actor)')).recordset[0]}),
 departmentOrders:(u,id,search)=>run(async p=>{if(!u.department)throw fail('กรุณาให้ Administrator กำหนด Department ของบัญชีก่อน',403);return(await p.request().input('dept',sql.NVarChar(50),u.department).input('id',sql.BigInt,id||null).input('search',sql.NVarChar(250),search?'%'+String(search)+'%':null).query(`SELECT TOP(5000) W.*,S.StatusCode,A.AssetName,A.MachineCode,A.TagNo FROM cmms.WorkOrder W LEFT JOIN ref.WorkOrderStatus S ON S.WorkOrderStatusID=W.WorkOrderStatusID LEFT JOIN cmms.Asset A ON A.AssetID=W.AssetID WHERE COALESCE(W.RequestDepartment,W.SectionName)=@dept AND (@id IS NULL OR W.WorkOrderID=@id) AND (@search IS NULL OR W.Title LIKE @search OR W.WorkOrderNo LIKE @search OR A.MachineCode LIKE @search) ORDER BY W.RequestedDate DESC,W.WorkOrderID DESC`)).recordset}),
 tagOrder:(u,id)=>run(async p=>{await p.request().input('id',sql.BigInt,id).input('dept',sql.NVarChar(50),u.department||null).input('name',sql.NVarChar(100),u.username).query('UPDATE cmms.WorkOrder SET RequestDepartment=@dept,CreatedBy=@name WHERE WorkOrderID=@id')})
 };
}
export function installWorkforce(app,service,getUsers,access,perform){
 const route=(allowed,fn)=>async(req,res)=>{if(!allowed(req))return res.status(403).json({ok:false,error:{message:'ไม่มีสิทธิ์ใช้ฟังก์ชันนี้'}});try{if(!service)throw fail('เชื่อมต่อฐานข้อมูลไม่ได้',503);res.json({ok:true,data:await fn(req)})}catch(e){res.status(e.status|| (e.number===50001?409:503)).json({ok:false,error:{message:e.status||e.number===50001?e.message:'เชื่อมต่อฐานข้อมูลไม่ได้'}})}};
 const stock=req=>access(req,'spare-parts');const manager=req=>['ADMINISTRATOR','PLANNER'].includes(req.user.role);
 app.get('/api/loans',route(stock,r=>service.listLoans(r.user)));app.post('/api/loans',route(r=>stock(r)&&perform(r,'stock-transactions','POST'),r=>service.borrow(r.user,r.body)));app.post('/api/loans/:id/resolve',route(r=>stock(r)&&perform(r,'stock-transactions','POST'),r=>service.resolveLoan(r.user,r.params.id,r.body)));
 app.get('/api/technicians',route(manager,async r=>({users:(await getUsers(r)).filter(u=>u.role==='TECHNICIAN'&&!u.deletedAt).map(({passwordHash,...u})=>u),overtime:await service.overtime()})));app.post('/api/technicians/overtime',route(manager,async r=>service.saveOvertime(r.user,r.body,await getUsers(r))));
}
