import {useState} from 'react';
import {str,value,type Row,type Resource} from './api';
import {SpareAnalytics} from './spare-analytics';
import {number,validDate,closed,active,late,group,maintenanceSummary,type ChartItem} from './report-data.mjs';
const categories=[['maintenance','ภาพรวม Maintenance'],['maintenance-plans','PM Plan'],['work-orders','Work Order'],['spare-parts','คลังอะไหล่']] as const;
const colors=['#3989e8','#ec9c36','#27b7a2','#9c7be8','#ed697d','#7c95aa'];
const fmt=(n:number)=>n.toLocaleString('th-TH',{maximumFractionDigits:1});
function Bars({title,items,unit='รายการ',limit=8,note}:{title:string;items:ChartItem[];unit?:string;limit?:number;note?:string}){
 const shown=items.slice(0,limit),max=Math.max(1,...shown.map(x=>x.value));
 return <section className="report-chart"><h3>{title}</h3>{note&&<p className="data-note">{note}</p>}{!shown.length?<p className="chart-empty">ไม่มีข้อมูลสำหรับกราฟนี้</p>:<div className="chart-bars">{shown.map((x,i)=><div className="chart-bar-row" key={x.label}><div className="chart-bar-heading"><span>{x.label}</span><strong>{fmt(x.value)} {unit}</strong></div><div className="chart-track" aria-hidden="true"><div style={{width:`${x.value/max*100}%`,background:colors[i%colors.length]}}/></div></div>)}</div>}{items.length>limit&&<p className="data-note">แสดง {limit} อันดับแรก จาก {items.length} กลุ่ม</p>}</section>
}
function Donut({title,items}:{title:string;items:ChartItem[]}){
 const total=items.reduce((n,x)=>n+x.value,0);let cursor=0;
 const segments=items.map((x,i)=>{const start=cursor;cursor+=total?x.value/total*100:0;return `${colors[i%colors.length]} ${start}% ${cursor}%`});
 return <section className="report-chart"><h3>{title}</h3>{!total?<p className="chart-empty">ไม่มีข้อมูลสำหรับกราฟนี้</p>:<div className="chart-donut-layout"><div className="chart-donut" aria-hidden="true" style={{background:`conic-gradient(${segments.join(',')})`}}><div><strong>{fmt(total)}</strong><span>รายการ</span></div></div><ul className="chart-legend">{items.map((x,i)=><li key={x.label}><i style={{background:colors[i%colors.length]}}/><span>{x.label}</span><strong>{fmt(x.value)} <small>({fmt(x.value/total*100)}%)</small></strong></li>)}</ul></div>}</section>
}
function Metrics({items}:{items:[string,number|null,string][]}){return <div className="category-metrics">{items.map(([label,n,unit])=><div className="panel" key={label}><span>{label}</span><strong>{n===null?'—':fmt(n)} <small>{unit}</small></strong></div>)}</div>}
export function CategoryReports({data,loading,error,onExport}:{data:Partial<Record<Resource,Row[]>>;loading:boolean;error?:Error;onExport:(rows:Row[],name:string)=>void}){
 const [category,setCategory]=useState<(typeof categories)[number][0]>('maintenance');
 const work=data['work-orders']||[],plans=data['maintenance-plans']||[],parts=data['spare-parts']||[],assets=data.assets||[];
 const summary=maintenanceSummary(work,assets),rows=category==='maintenance'?work:data[category]||[];
 const pmStatus=group(plans,r=>!active(r)?'ปิดใช้งาน':!validDate(value(r,'NextDueDate'))?'ไม่ระบุกำหนด':late(r,'NextDueDate')?'เกินกำหนด':'ยังไม่ถึงกำหนด');
 const stockStatus=(r:Row)=>{const qty=number(r,'Quantity'),reorder=number(r,'ReorderPoint'),min=number(r,'MinimumStock');return qty===null?'ไม่ระบุจำนวน':qty<=0?'หมดสต็อก':((reorder!==null&&qty<=reorder)||(min!==null&&qty<min))?'ต้องเติมสต็อก':min===null&&reorder===null?'ไม่ระบุเกณฑ์ขั้นต่ำ':'เพียงพอ'};
 return <section className="panel report-panel"><h2>รายงานและวิเคราะห์</h2><div className="report-category-tabs">{categories.map(([id,label])=><button key={id} className={`button ${category===id?'primary':''}`} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div>{loading?<p role="status">กำลังโหลดสรุป…</p>:error?<p role="alert" className="error-box">{error.message}</p>:<><p className="data-note">สรุปข้อมูลที่โหลดสูงสุด 2,000 รายการต่อหมวดหมู่ · ทุกช่วงเวลา · กราฟและตัวเลขอาจไม่ครอบคลุมข้อมูลทั้งหมดในฐานข้อมูล</p>
 {category==='maintenance'?<><Metrics items={[["Downtime รวม",summary.measured?summary.totalHours:null,'ชม.'],['เครื่องจักรมี Downtime',summary.machines.length,'กลุ่ม'],['งานค้าง',work.filter(r=>!closed(r)).length,'งาน'],['PM เกินกำหนด',plans.filter(r=>active(r)&&late(r,'NextDueDate')).length,'แผน'],['เวลางานซ่อมเฉลี่ย',summary.meanRepairHours,'ชม.']]}/><p className="data-note">Downtime ใช้ค่าที่บันทึกในใบงาน {summary.measured} / {summary.jobs.length} งาน ไม่รวมงานยกเลิก · ขาดข้อมูล {summary.missing} งาน · เวลางานซ่อมเฉลี่ยใช้เวลาเริ่ม–จบจริงของงานเสร็จ {summary.durationCount} งาน ผลรวม Downtime อาจมีช่วงเวลาซ้อนกันระหว่างใบงาน</p><div className="report-chart-grid"><Bars title="เครื่องจักรที่มี Downtime สูงสุด" items={summary.machines} unit="ชม."/><Bars title="แนวโน้ม Downtime รายเดือน" items={summary.trend} unit="ชม." limit={12} note="12 เดือนจนถึงเดือนล่าสุดที่มีข้อมูล อ้างอิงเดือนเริ่มงานจริง หรือเดือนแจ้งซ่อมเมื่อไม่มีวันเริ่มงาน เดือนที่ไม่มีรายการในข้อมูลที่โหลดแสดงเป็น 0"/><Donut title="งานซ่อมแยกตามประเภท" items={group(work,r=>str(r,'WorkTypeCode'))}/><Donut title="สถานะแผน PM" items={pmStatus}/></div>{summary.undated>0&&<p className="data-note">{summary.undated} งานมี Downtime แต่ไม่มีวันที่ที่ใช้ได้ จึงไม่รวมในแนวโน้มรายเดือน</p>}</>:
 category==='maintenance-plans'?<><Metrics items={[["แผนทั้งหมด",plans.length,'แผน'],['เปิดใช้งาน',plans.filter(active).length,'แผน'],['เกินกำหนด',plans.filter(r=>active(r)&&late(r,'NextDueDate')).length,'แผน']]}/><div className="report-chart-grid"><Donut title="สถานะแผน PM" items={pmStatus}/><Bars title="รอบความถี่ PM" items={group(plans,r=>[str(r,'FrequencyValue'),str(r,'FrequencyUnitCode')||str(r,'FrequencyUnit')].filter(Boolean).join(' '))} unit="แผน"/><Bars title="ประเภทการบำรุงรักษา" items={group(plans,r=>str(r,'MaintenanceType')||str(r,'MaintenanceTypeCode'))} unit="แผน"/></div></>:
 category==='work-orders'?<><Metrics items={[["ใบงานทั้งหมด",work.length,'งาน'],['งานที่ยังเปิด',work.filter(r=>!closed(r)).length,'งาน'],['งานเกินกำหนด',work.filter(r=>!closed(r)&&late(r,'DueDate')).length,'งาน']]}/><div className="report-chart-grid"><Donut title="สถานะใบงาน" items={group(work,r=>str(r,'StatusCode'))}/><Bars title="ประเภทงานซ่อม" items={group(work,r=>str(r,'WorkTypeCode'))} unit="งาน"/><Bars title="ความเร่งด่วนของงานค้าง" items={group(work.filter(r=>!closed(r)),r=>str(r,'PriorityCode'))} unit="งาน"/></div></>:
 <><Metrics items={[["อะไหล่ทั้งหมด",parts.length,'รายการ'],['หมดสต็อก',parts.filter(r=>stockStatus(r)==='หมดสต็อก').length,'รายการ'],['ต้องเติมสต็อก (รวมหมด)',parts.filter(r=>['หมดสต็อก','ต้องเติมสต็อก'].includes(stockStatus(r))).length,'รายการ']]}/><div className="report-chart-grid"><Donut title="สถานะคลังอะไหล่" items={group(parts,stockStatus)}/><Bars title="อะไหล่แยกตาม Department" items={group(parts,r=>str(r,'Department'))}/><Bars title="อะไหล่แยกตาม Part Type" items={group(parts,r=>str(r,'PartType'))}/></div><SpareAnalytics rows={parts}/></>}
 <button className="button" disabled={!rows.length} onClick={()=>onExport(rows,category==='maintenance'?'maintenance-work-orders':category)}>{category==='maintenance'?'ส่งออกใบงานสำหรับวิเคราะห์':'ส่งออกหมวดหมู่นี้'}</button></>}</section>
}
