import {useState} from 'react';
import {str,num,value,validDate,type Row,type Resource} from './api';
import {SpareAnalytics} from './spare-analytics';
const categories = [['maintenance-plans','PM Plan'],['work-orders','Work Order'],['spare-parts','คลังอะไหล่']] as const;
export function CategoryReports({data,loading,error,onExport}:{data:Partial<Record<Resource,Row[]>>;loading:boolean;error?:Error;onExport:(rows:Row[],name:string)=>void}){
 const [category,setCategory]=useState<Resource>('maintenance-plans');
 const rows=data[category]||[];
 const closed=(r:Row)=>['COMPLETED','CANCELLED','CLOSED'].includes(str(r,'StatusCode').toUpperCase());
 const late=(r:Row,key:string)=>validDate(value(r,key))&&new Date(str(r,key)).getTime()<new Date(new Date().toDateString()).getTime();
 const active=(r:Row)=>!['false','0'].includes(str(r,'IsActive').toLowerCase());
 const metrics: [string,number][] = category==='maintenance-plans' ? [['แผนทั้งหมด',rows.length],['แผนที่เปิดใช้งาน',rows.filter(active).length],['แผนเกินกำหนด',rows.filter(r=>active(r)&&late(r,'NextDueDate')).length]] : category==='work-orders' ? [['ใบงานทั้งหมด',rows.length],['งานที่ยังเปิด',rows.filter(r=>!closed(r)).length],['งานเกินกำหนด',rows.filter(r=>!closed(r)&&late(r,'DueDate')).length],['งานเสร็จแล้ว',rows.filter(r=>['COMPLETED','CLOSED'].includes(str(r,'StatusCode').toUpperCase())).length]] : [['อะไหล่ทั้งหมด',rows.length],['สต็อกหมด',rows.filter(r=>value(r,'Quantity')!==null&&num(r,'Quantity')<=0).length],['ต้องเติมสต็อก',rows.filter(r=>value(r,'Quantity')!==null&&((value(r,'ReorderPoint')!==null&&num(r,'Quantity')<=num(r,'ReorderPoint'))||(value(r,'MinimumStock')!==null&&num(r,'Quantity')<num(r,'MinimumStock')))).length]];
 const key=category==='maintenance-plans'?'FrequencyUnitCode':category==='work-orders'?'StatusCode':'Department';
 const groups=rows.reduce<Record<string,number>>((out,row)=>{const label=str(row,key)||'ไม่ระบุ';out[label]=(out[label]||0)+1;return out},{});
 return <section className="panel report-panel"><h2>รายงานและวิเคราะห์</h2><div className="report-category-tabs">{categories.map(([id,label])=><button key={id} className={`button ${category===id?'primary':''}`} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div>{loading?<p role="status">กำลังโหลดสรุป…</p>:error?<p role="alert" className="error-box">{error.message}</p>:<><p className="data-note">สรุปจากข้อมูลที่โหลด {rows.length.toLocaleString()} รายการ (สูงสุด 2,000 รายการต่อหมวดหมู่)</p><div className="category-metrics">{metrics.map(([label,count])=><div className="panel" key={label}><span>{label}</span><strong>{count.toLocaleString()}</strong></div>)}</div><h3>แยกตาม {category==='maintenance-plans'?'รอบความถี่':category==='work-orders'?'สถานะ':'Department'}</h3><table><thead><tr><th>หมวดหมู่</th><th>จำนวน</th></tr></thead><tbody>{Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([label,count])=><tr key={label}><td>{label}</td><td>{count.toLocaleString()}</td></tr>)}</tbody></table>{!rows.length&&<p>ไม่พบข้อมูลในหมวดหมู่นี้</p>}{category==='spare-parts'&&<SpareAnalytics rows={rows}/>}<button className="button" disabled={!rows.length} onClick={()=>onExport(rows,category)}>ส่งออกหมวดหมู่นี้</button></>}</section>
}
