import {issueSequentially} from './issue-batch.mjs';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {api,canWrite,str,num,type Row,type Role} from './api';
type Line={row:Row;quantity:string;state:'pending'|'saved'|'uncertain';message?:string;transactionId?:string};
export function IssueParts({initial=[],role,onSaved,onConsumed,cartOnly=false,onCount}:{initial?:Row[];onConsumed?:()=>void;cartOnly?:boolean;onCount?:(count:number)=>void;role:Role|undefined;onSaved:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[search,setSearch]=useState(''),[lines,setLines]=useState<Line[]>(()=>initial.map(row=>({row,quantity:'1',state:'pending'}))),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [warehouses,setWarehouses]=useState<Row[]>([]),[warehouse,setWarehouse]=useState(''),[reference,setReference]=useState(''),[remark,setRemark]=useState('');
 const [type,setType]=useState('ISSUE'),[workOrder,setWorkOrder]=useState(''),[workOrders,setWorkOrders]=useState<Row[]>([]);
 const lock=useRef(false);
 useEffect(()=>{api('work-orders',{limit:5000}).then(j=>setWorkOrders(j.data)).catch(()=>{})},[]);
 const searchInput=useRef<HTMLInputElement>(null);
 useEffect(()=>onCount?.(lines.length),[lines.length]);
 useEffect(()=>{if(initial.length){if(lock.current||lines.some(l=>l.state!=='pending')){setError('กรุณาเริ่มรายการใหม่ก่อนเพิ่มอะไหล่');onConsumed?.();return;}setLines(prev=>[...prev,...initial.filter(row=>!prev.some(l=>str(l.row,'PartID')===str(row,'PartID'))).map(row=>({row,quantity:'1',state:'pending' as const}))]);onConsumed?.()}},[initial]);
 const allowed=canWrite(role,'POST','stock-transactions');
 useEffect(()=>{if(cartOnly)return;const ctrl=new AbortController();const timer=setTimeout(()=>{setLoading(true);api('spare-parts',{search,limit:5000},'GET',undefined,ctrl.signal).then(j=>{setRows(j.data);setError('')}).catch(e=>{if(!ctrl.signal.aborted)setError(e.message)}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false)})},250);return()=>{clearTimeout(timer);ctrl.abort()}},[search,cartOnly]);
 useEffect(()=>{fetch('/api/lookups').then(async r=>{if(!r.ok)throw Error('โหลดคลังไม่ได้');return r.json()}).then(j=>setWarehouses(j.warehouses)).catch(e=>setError(e.message))},[]);
 const add=(row:Row)=>setLines(prev=>prev.some(l=>str(l.row,'PartID')===str(row,'PartID'))?prev:[...prev,{row,quantity:'1',state:'pending'}]);
 async function submit(e:React.FormEvent){e.preventDefault();if(lock.current||!allowed)return;if(type==='RECEIVE'&&!['ADMINISTRATOR','PLANNER'].includes(role||'')){setError('ไม่มีสิทธิ์เติมสต็อก');return;}const pending=lines.filter(l=>l.state==='pending');if(!pending.length)return;
  if(!Number.isInteger(Number(warehouse))||Number(warehouse)<=0){setError('กรุณาเลือกคลังอะไหล่');return}
  if(pending.some(l=>!Number.isFinite(Number(l.quantity))||Number(l.quantity)<=0)){setError('กรุณาระบุจำนวนมากกว่า 0 ทุกรายการ');return}
  lock.current=true;setBusy(true);setError('');
  const savedIds=new Map<string,string>();
  const saved=await issueSequentially(lines, async line=>{
   const result=await api('stock-transactions',{},'POST',{transactionTypeCode:type,...(workOrder?{workOrderId:Number(workOrder)}:{}),partId:Number(str(line.row,'PartID')),warehouseId:Number(warehouse),quantity:Number(line.quantity),...(reference?{referenceNo:reference}:{}),...(remark?{remark}:{})});
   const records=Array.isArray(result.data)?result.data:[result.data];const id=String(records[0]?.StockTransactionID||'');
   if(!id)throw Error('บันทึกแล้วแต่ไม่พบเลขรายการ กรุณาตรวจประวัติ');
   savedIds.set(str(line.row,'PartID'),id);
  },(line,state,failure)=>setLines(prev=>prev.map(l=>str(l.row,'PartID')===str(line.row,'PartID')?{...l,state,transactionId:savedIds.get(str(line.row,'PartID')),message:state==='saved'?'บันทึกสำเร็จ':((failure as Error)?.message||'ไม่สามารถยืนยันผลบันทึก')+' · ตรวจประวัติก่อนทำรายการซ้ำ'}:l)));


  if(saved)onSaved();lock.current=false;setBusy(false);
 }
 return <section className="panel report-panel"><h2>ตะกร้าทำรายการ ({lines.length})</h2>{error&&<p className="error-box" role="alert">{error}</p>}{!cartOnly&&<><div className="issue-search"><input ref={searchInput} aria-label="ค้นหาอะไหล่เพื่อเบิก" placeholder="ค้นหารหัสหรือชื่ออะไหล่" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button type="button" className="issue-search-clear" aria-label="ล้างคำค้นหาอะไหล่" title="ล้างคำค้นหา" onClick={()=>{setSearch('');searchInput.current?.focus()}}><X size={18} aria-hidden="true"/></button>}</div>{loading?<p role="status">กำลังโหลดอะไหล่…</p>:<div className="issue-picker">{rows.map(row=><button type="button" className="issue-choice" key={str(row,'PartID')} disabled={busy||!allowed||lines.some(l=>str(l.row,'PartID')===str(row,'PartID'))} onClick={()=>add(row)}><strong>{str(row,'PartCode')}</strong><span>{str(row,'PartName')}</span><small>Location: {str(row,'CabinetClass')||'ไม่ระบุ'}</small><small>คงเหลือ {num(row,'Quantity').toLocaleString()} {str(row,'Unit')}</small></button>)}{!rows.length&&<p>ไม่พบอะไหล่</p>}</div>}
 </>}<form onSubmit={submit}><h3>รายการที่เลือก ({lines.length})</h3><div className="table-scroll"><table><thead><tr><th>อะไหล่</th><th>จำนวนทำรายการ</th><th>ผลบันทึก</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={str(l.row,'PartID')}><td>{str(l.row,'PartCode')} · {str(l.row,'PartName')}</td><td><input type="number" min="0.000001" step="any" required aria-label={`จำนวนทำรายการ ${str(l.row,'PartCode')}`} disabled={busy||l.state==='saved'||l.state==='uncertain'} value={l.quantity} onChange={e=>setLines(prev=>prev.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))}/></td><td role="status">{l.message||'รอบันทึก'}{l.transactionId&&<><a href="#stock-transactions">ดูประวัติ</a></>}</td><td>{l.state==='pending'&&<button type="button" className="button" disabled={busy} onClick={()=>setLines(prev=>prev.filter((_,n)=>n!==i))}>เอาออก</button>}</td></tr>)}</tbody></table></div><div className="issue-fields"><label>ประเภท<select aria-label="ประเภท" value={type} disabled={busy||lines.some(l=>l.state!=='pending')} onChange={e=>setType(e.target.value)}><option value="ISSUE">เบิกอะไหล่</option><option value="RETURN">คืนอะไหล่</option>{['ADMINISTRATOR','PLANNER'].includes(role||'')&&<option value="RECEIVE">เติมสต็อก</option>}</select></label><label>เชื่อมใบงาน / Issue<select aria-label="เชื่อมใบงาน / Issue" value={workOrder} disabled={busy||lines.some(l=>l.state!=='pending')} onChange={e=>setWorkOrder(e.target.value)}><option value="">ไม่เชื่อมใบงาน</option>{workOrders.map(w=><option key={str(w,'WorkOrderID')} value={str(w,'WorkOrderID')}>{str(w,'WorkOrderNo')} · {str(w,'Title')}</option>)}</select></label><label>คลังอะไหล่<select required aria-label="คลังสำหรับเบิก" disabled={busy||lines.some(l=>l.state!=='pending')} value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">เลือกคลัง</option>{warehouses.map(w=><option key={str(w,'WarehouseID')} value={str(w,'WarehouseID')}>{str(w,'WarehouseName')}</option>)}</select></label><label>เอกสารอ้างอิง<input value={reference} disabled={busy||lines.some(l=>l.state!=='pending')} onChange={e=>setReference(e.target.value)}/></label><label>หมายเหตุ<input value={remark} disabled={busy||lines.some(l=>l.state!=='pending')} onChange={e=>setRemark(e.target.value)}/></label></div><p className="data-note">บันทึกแยกทีละรายการ รายการที่สำเร็จแล้วจะไม่ถูกส่งซ้ำ หากการเชื่อมต่อขัดข้องให้ตรวจประวัติรับ–เบิกก่อนทำรายการนั้นใหม่</p><button className="button primary" disabled={busy||!allowed||!lines.some(l=>l.state==='pending')}>{busy?'กำลังบันทึก…':'บันทึกรายการที่เลือก'}</button><button type="button" className="button" disabled={busy||!lines.length} onClick={()=>{setLines([]);setWorkOrder('');setWarehouse('');setReference('');setRemark('');setError('')}}>เริ่มรายการใหม่</button></form></section>;
}
