import {issueSequentially} from './issue-batch.mjs';
import {useEffect,useRef,useState} from 'react';
import {api,canWrite,str,num,type Row,type Role} from './api';
type Line={row:Row;quantity:string;state:'pending'|'saved'|'uncertain';message?:string};
export function IssueParts({initial=[],role,onSaved,onConsumed}:{initial?:Row[];onConsumed?:()=>void;role:Role|undefined;onSaved:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[search,setSearch]=useState(''),[lines,setLines]=useState<Line[]>(()=>initial.map(row=>({row,quantity:'1',state:'pending'}))),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [warehouses,setWarehouses]=useState<Row[]>([]),[warehouse,setWarehouse]=useState(''),[reference,setReference]=useState(''),[remark,setRemark]=useState('');
 const lock=useRef(false);
 useEffect(()=>{onConsumed?.()},[]);
 const allowed=canWrite(role,'POST','stock-transactions');
 useEffect(()=>{const ctrl=new AbortController();const timer=setTimeout(()=>{setLoading(true);api('spare-parts',{search,limit:2000},'GET',undefined,ctrl.signal).then(j=>{setRows(j.data);setError('')}).catch(e=>{if(!ctrl.signal.aborted)setError(e.message)}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false)})},250);return()=>{clearTimeout(timer);ctrl.abort()}},[search]);
 useEffect(()=>{fetch('/api/lookups').then(async r=>{if(!r.ok)throw Error('โหลดคลังไม่ได้');return r.json()}).then(j=>setWarehouses(j.warehouses)).catch(e=>setError(e.message))},[]);
 const add=(row:Row)=>setLines(prev=>prev.some(l=>str(l.row,'PartID')===str(row,'PartID'))?prev:[...prev,{row,quantity:'1',state:'pending'}]);
 async function submit(e:React.FormEvent){e.preventDefault();if(lock.current||!allowed)return;const pending=lines.filter(l=>l.state==='pending');if(!pending.length)return;
  if(!Number.isInteger(Number(warehouse))||Number(warehouse)<=0){setError('กรุณาเลือกคลังอะไหล่');return}
  if(pending.some(l=>!Number.isFinite(Number(l.quantity))||Number(l.quantity)<=0)){setError('กรุณาระบุจำนวนมากกว่า 0 ทุกรายการ');return}
  lock.current=true;setBusy(true);setError('');const saved=await issueSequentially(lines, line=>api('stock-transactions',{},'POST',{transactionTypeCode:'ISSUE',partId:Number(str(line.row,'PartID')),warehouseId:Number(warehouse),quantity:Number(line.quantity),...(reference?{referenceNo:reference}:{}),...(remark?{remark}:{})}), (line,state,failure)=>setLines(prev=>prev.map(l=>str(l.row,'PartID')===str(line.row,'PartID')?{...l,state,message:state==='saved'?'เบิกสำเร็จ':((failure as Error)?.message||'ไม่สามารถยืนยันผลบันทึก')+' · ตรวจประวัติก่อนทำรายการซ้ำ'}:l)));
  if(saved)onSaved();lock.current=false;setBusy(false);
 }
 return <section className="panel report-panel"><h2>เลือกอะไหล่เพื่อเบิก</h2><p>คลิกรายการเพื่อเพิ่มในตะกร้า แล้วระบุจำนวนที่ต้องการเบิก</p>{error&&<p className="error-box" role="alert">{error}</p>}<input aria-label="ค้นหาอะไหล่เพื่อเบิก" placeholder="ค้นหารหัสหรือชื่ออะไหล่" value={search} onChange={e=>setSearch(e.target.value)}/>{loading?<p role="status">กำลังโหลดอะไหล่…</p>:<div className="issue-picker">{rows.map(row=><button type="button" className="issue-choice" key={str(row,'PartID')} disabled={busy||!allowed||lines.some(l=>str(l.row,'PartID')===str(row,'PartID'))} onClick={()=>add(row)}><strong>{str(row,'PartCode')}</strong><span>{str(row,'PartName')}</span><small>คงเหลือ {num(row,'Quantity').toLocaleString()} {str(row,'Unit')}</small></button>)}{!rows.length&&<p>ไม่พบอะไหล่</p>}</div>}
 <form onSubmit={submit}><h3>รายการที่เลือก ({lines.length})</h3><div className="table-scroll"><table><thead><tr><th>อะไหล่</th><th>จำนวนเบิก</th><th>ผลบันทึก</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={str(l.row,'PartID')}><td>{str(l.row,'PartCode')} · {str(l.row,'PartName')}</td><td><input type="number" min="0.000001" step="any" required aria-label={`จำนวนเบิก ${str(l.row,'PartCode')}`} disabled={busy||l.state==='saved'||l.state==='uncertain'} value={l.quantity} onChange={e=>setLines(prev=>prev.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))}/></td><td role="status">{l.message||'รอบันทึก'}</td><td>{l.state==='pending'&&<button type="button" className="button" disabled={busy} onClick={()=>setLines(prev=>prev.filter((_,n)=>n!==i))}>เอาออก</button>}</td></tr>)}</tbody></table></div><div className="issue-fields"><label>คลังอะไหล่<select required aria-label="คลังสำหรับเบิก" disabled={busy||lines.some(l=>l.state!=='pending')} value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">เลือกคลัง</option>{warehouses.map(w=><option key={str(w,'WarehouseID')} value={str(w,'WarehouseID')}>{str(w,'WarehouseName')}</option>)}</select></label><label>เอกสารอ้างอิง<input value={reference} disabled={busy} onChange={e=>setReference(e.target.value)}/></label><label>หมายเหตุ<input value={remark} disabled={busy} onChange={e=>setRemark(e.target.value)}/></label></div><p className="data-note">บันทึกแยกทีละรายการ รายการที่สำเร็จแล้วจะไม่ถูกส่งซ้ำ หากการเชื่อมต่อขัดข้องให้ตรวจประวัติรับ–เบิกก่อนทำรายการนั้นใหม่</p><button className="button primary" disabled={busy||!allowed||!lines.some(l=>l.state==='pending')}>{busy?'กำลังบันทึก…':'เบิกรายการที่เลือก'}</button><button type="button" className="button" disabled={busy||!lines.length} onClick={()=>{setLines([]);setWarehouse('');setReference('');setRemark('');setError('')}}>เริ่มรายการเบิกใหม่</button></form></section>;
}
