import {useEffect,useRef,useState} from 'react';
import {canWrite,display,str,type Role,type Row} from './api';
async function request(path:string,options?:RequestInit){const r=await fetch(path,options);const j=await r.json();if(r.status===401)window.dispatchEvent(new Event('cmms-session-expired'));if(!r.ok||!j.ok)throw Error(j.error?.message||'โหลดข้อมูลไม่สำเร็จ');return j.data}
function useData(path:string,refresh=0){const [data,setData]=useState<any>(),[error,setError]=useState('');useEffect(()=>{const ctrl=new AbortController();setError('');setData(undefined);request(path,{signal:ctrl.signal}).then(setData).catch(e=>{if(!ctrl.signal.aborted)setError(e.message)});return()=>ctrl.abort()},[path,refresh]);return {data,error}}
const fields=[['VendorName','ชื่อ Vendor',150],['VendorCode','รหัส Vendor',50],['ContactName','ผู้ติดต่อ',150],['Phone','โทรศัพท์',80],['Email','อีเมล',255]] as const;
export function PartHistory({id}:{id:string}){
 const [page,setPage]=useState(1),[retry,setRetry]=useState(0);
 const {data,error}=useData('/api/parts/'+encodeURIComponent(id)+'/history?page='+page,retry);
 const labels:Record<string,string>={RECEIVE:'รับเข้า',ISSUE:'เบิก',RETURN:'คืน',ADJUST_IN:'ปรับเพิ่ม',ADJUST_OUT:'ปรับลด',TRANSFER_IN:'โอนเข้า',TRANSFER_OUT:'โอนออก',OPENING:'ยอดตั้งต้น'};
 return <section className="panel report-panel"><h3>ประวัติการเคลื่อนไหว</h3>{data&&<p className="data-note">{data.material?'SAP Material '+data.material:'อ้างอิงทะเบียนอะไหล่นี้ (ไม่มี SAP Material)'} · {data.total.toLocaleString()} รายการ · ล่าสุดก่อน</p>}
 {error?<div role="alert"><p>{error}</p><button className="button" onClick={()=>setRetry(n=>n+1)}>ลองใหม่</button></div>:!data?<p role="status">กำลังโหลดประวัติ…</p>:<>
 {!data.total?<p>ยังไม่มีประวัติการเคลื่อนไหว</p>:<div className="table-scroll"><table><thead><tr><th>วันที่</th><th>เลขเอกสาร SAP</th><th>ประเภท</th><th>จำนวน</th><th>ใบเบิก / อ้างอิง</th><th>รายละเอียด</th></tr></thead><tbody>{data.rows.map((r:Row)=><tr key={str(r,'StockTransactionID')}><td>{display(r.TransactionDate,'TransactionDate')}</td><td>{str(r,'SAPDocumentNo')||'—'}</td><td>{labels[str(r,'TypeCode')]||str(r,'TypeCode')}</td><td>{Number(r.QuantitySign)>0?'+':'−'}{Number(r.Quantity).toLocaleString('th-TH',{maximumFractionDigits:4})}</td><td>{str(r,'RequestNumber')||str(r,'ReferenceNo')||'—'}</td><td><details><summary>ดูรายละเอียด</summary><p>รหัสอะไหล่: {str(r,'PartCode')}<br/>เครื่องจักร: {str(r,'MachineCodeText')||'—'}<br/>ผู้รับ: {str(r,'IssuedTo')||'—'}<br/>{r.IsHistorical?'ประวัติย้อนหลัง':'รายการเคลื่อนไหว'}</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{movementRemark(str(r,'Remark'))}</p></details></td></tr>)}</tbody></table></div>}
 <div className="report-toolbar"><button className="button" disabled={page<=1} onClick={()=>setPage(n=>n-1)}>ก่อนหน้า</button><span>หน้า {page} / {Math.max(1,Math.ceil(data.total/data.pageSize))}</span><button className="button" disabled={page*data.pageSize>=data.total} onClick={()=>setPage(n=>n+1)}>ถัดไป</button></div></>}
 </section>;
}
function movementRemark(text:string){try{const r=JSON.parse(text);return [r.detail,r.SAPMovementType&&'SAP Movement: '+r.SAPMovementType,r.postingTime&&'เวลา: '+r.postingTime,r.amountLC!==undefined&&'มูลค่ารายการ: '+Number(r.amountLC).toLocaleString('th-TH')+' '+(r.currency||'')].filter(Boolean).join('\n')||text}catch{return text||'—'}}
export function VendorList({role,refresh}:{role:Role|undefined;refresh:number}){
 const [retry,setRetry]=useState(0),[search,setSearch]=useState(''),[edit,setEdit]=useState<Row|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 const {data,error}=useData('/api/vendors',refresh+retry);const rows:Row[]=data||[];
 const can=(method:string)=>['ADMINISTRATOR','PLANNER'].includes(role||'')&&canWrite(role,method,'maintenance-plans');
 const filtered=rows.filter(r=>fields.some(([k])=>str(r,k).toLowerCase().includes(search.toLowerCase())));
 async function save(e:React.FormEvent){e.preventDefault();if(!edit||lock.current||!can(edit.VendorID?'PUT':'POST'))return;lock.current=true;setBusy(true);setMessage('');try{const body=Object.fromEntries([...fields.map(([k])=>[k,edit[k]??'']),['IsActive',edit.IsActive===true],...(edit.VendorID?[['Version',edit.Version]]:[])]);await request('/api/vendors'+(edit.VendorID?'/'+edit.VendorID:''),{method:edit.VendorID?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setEdit(null);setRetry(n=>n+1);setMessage('บันทึก Vendor แล้ว')}catch(e){setMessage((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 return <section className="panel report-panel"><div className="report-toolbar"><h2>Vendor list</h2><button className="button primary" disabled={!can('POST')||busy} onClick={()=>{setEdit({IsActive:true});setMessage('')}}>เพิ่ม Vendor</button></div><p className="data-note">สิทธิ์ดูอิงแผนบำรุงรักษา · เพิ่ม/แก้ไขสำหรับ Administrator และ Planner ที่มีสิทธิ์เพิ่ม/แก้ไขแผน · ใช้สถานะปิดใช้งานเมื่อเลิกใช้ Vendor</p>{error&&<p role="alert" className="error-box">{error}</p>}{message&&<p role="status">{message}</p>}{edit&&<form onSubmit={save} className="vendor-editor"><h3>{edit.VendorID?'แก้ไข':'เพิ่ม'} Vendor</h3><div className="issue-fields">{fields.map(([key,label,max])=><label key={key}>{label}<input type={key==='Email'?'email':'text'} maxLength={max} required={key==='VendorName'} disabled={busy} value={str(edit,key)} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}</div><label><input type="checkbox" checked={edit.IsActive===true} disabled={busy} onChange={e=>setEdit({...edit,IsActive:e.target.checked})}/> เปิดใช้งาน</label><div className="report-toolbar"><button className="button primary" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึก'}</button><button type="button" className="button" disabled={busy} onClick={()=>setEdit(null)}>ยกเลิก</button></div></form>}<input className="master-search" aria-label="ค้นหา Vendor" placeholder="ค้นหาชื่อ รหัส หรือผู้ติดต่อ" value={search} onChange={e=>setSearch(e.target.value)}/><p>{data?`${filtered.length} / ${rows.length} รายการ`:'กำลังโหลด…'}</p><div className="table-scroll"><table><thead><tr>{fields.map(([k,label])=><th key={k}>{label}</th>)}<th>สถานะ</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={str(r,'VendorID')}>{fields.map(([k])=><td key={k}>{str(r,k)||'—'}</td>)}<td>{r.IsActive?'ใช้งาน':'ปิดใช้งาน'}</td><td><button className="button" disabled={!can('PUT')||busy} onClick={()=>{setEdit({...r});setMessage('')}}>แก้ไข</button></td></tr>)}</tbody></table></div></section>
}
export function CalibrationPoints({refresh,eventId}:{refresh:number;eventId?:string}){
 const {data,error}=useData('/api/calibration-points'+(eventId?'?eventId='+encodeURIComponent(eventId):''),refresh);const [search,setSearch]=useState('');const rows:Row[]=data||[];
 const specs=new Map<string,Row[]>();for(const row of rows){const key=str(row,'CalibrationSpecID');specs.set(key,[...(specs.get(key)||[]),row])}
 const filtered=[...specs.values()].filter(list=>['TagNo','MachineCode','AssetName','Description'].some(k=>str(list[0],k).toLowerCase().includes(search.toLowerCase())));
 return <section className="panel report-panel"><h2>จุดสอบเทียบ CAL_1 / CAL_2</h2><p className="data-note">ค่ากำหนด Setpoint จาก CalibrationPoint (PointNo = หมายเลข CAL) ไม่ใช่ผลวัดหรือผล PASS/FAIL · แสดงเฉพาะจุดที่มีในฐานข้อมูล ไม่มีการเติมค่า End หรือหน่วยที่ไม่ได้บันทึก</p>{error&&<p role="alert" className="error-box">{error}</p>}{!eventId&&<input className="master-search" aria-label="ค้นหาจุดสอบเทียบ" placeholder="ค้นหา Tag, Machine code หรือชื่อเครื่องจักร" value={search} onChange={e=>setSearch(e.target.value)}/>}<p>{data?`${filtered.length} / ${specs.size} ชุดข้อกำหนด · ${rows.filter(r=>r.PointNo!==null).length} จุด`:'กำลังโหลด…'}</p>{data&&filtered.length===0&&<p>ไม่พบจุดสอบเทียบที่เชื่อมกับ Record นี้</p>}<div className="calibration-specs">{filtered.map(list=>{const row=list[0];return <details open={eventId?true:undefined} key={str(row,'CalibrationSpecID')}><summary>{str(row,'TagNo')||str(row,'MachineCode')||'ไม่ระบุรหัส'} · {str(row,'AssetName')} · {list.filter(r=>r.PointNo!==null).length} จุด {row.IsActive?'':'(ปิดใช้งาน)'}</summary><p>{str(row,'Description')}</p><div className="table-scroll"><table><thead><tr>{list.filter(r=>r.PointNo!==null).map(r=><th key={str(r,'PointNo')}>CAL_{str(r,'PointNo')}</th>)}</tr></thead><tbody><tr>{list.filter(r=>r.PointNo!==null).map(r=><td key={str(r,'PointNo')}>{r.SetpointValue===null?'—':str(r,'SetpointValue')}</td>)}</tr></tbody></table></div>{row.PointNo===null&&<p>ไม่มีจุดสอบเทียบในฐานข้อมูล</p>}</details>})}</div></section>
}
export function PMHistory({refresh}:{refresh:number}){
 const {data,error}=useData('/api/pm-history',refresh);const [search,setSearch]=useState(''),[tab,setTab]=useState('PM');
 const work:Row[]=data?.completedWorkOrders||[],plans:Row[]=data?.lastPlanDates||[];const filter=(r:Row)=>['AssetName','TagNo','MachineCode','PlanCode','TaskDescription','Title'].some(k=>str(r,k).toLowerCase().includes(search.toLowerCase()));
 const filtered=plans.filter(r=>str(r,'TypeCode')===tab&&filter(r));
 return <section className="panel report-panel"><h2>ประวัติ PM</h2>{error&&<p role="alert" className="error-box">{error}</p>}{!data&&!error&&<p>กำลังโหลด…</p>}<input className="master-search" aria-label="ค้นหาประวัติ PM" placeholder="ค้นหาเครื่องจักร แผน หรืองาน" value={search} onChange={e=>setSearch(e.target.value)}/><h3>ใบงาน PM ที่เสร็จแล้ว ({work.length})</h3>{data&&!work.length&&<p className="report-data-warning">ยังไม่พบใบงานที่เสร็จและระบุประเภท PM หรือเชื่อมกับแผน PM ในฐานข้อมูล</p>}<div className="table-scroll"><table><thead><tr><th>ใบงาน</th><th>เครื่องจักร</th><th>งาน</th><th>เสร็จจริง</th><th>การดำเนินการ</th></tr></thead><tbody>{work.filter(filter).map(r=><tr key={str(r,'WorkOrderID')}><td>{str(r,'WorkOrderNo')}</td><td>{str(r,'TagNo')||str(r,'MachineCode')} {str(r,'AssetName')}</td><td>{str(r,'Title')}</td><td>{display(r.ActualFinish,'ActualFinish')}</td><td>{str(r,'ActionTaken')||'—'}</td></tr>)}</tbody></table></div><h3>วันที่ทำล่าสุดจากแผนบำรุงรักษา</h3><p className="data-note">ข้อมูล LastMaintenanceDate เป็นวันที่ล่าสุดของแต่ละแผน ไม่ใช่ประวัติครบทุกครั้ง และไม่ได้ยืนยันรายละเอียดงานหรือผลสอบเทียบ</p><div className="report-category-tabs">{[...new Set(['PM','INSPECTION','CALIBRATION',...plans.map(r=>str(r,'TypeCode')||'ไม่ระบุ')])].map(type=><button className="button" aria-pressed={type===tab} key={type} onClick={()=>setTab(type)}>{type} ({plans.filter(r=>str(r,'TypeCode')===type).length})</button>)}</div><p>{filtered.length} รายการ · เรียงล่าสุดก่อน</p><div className="table-scroll"><table><thead><tr><th>วันที่ล่าสุด</th><th>แผน</th><th>Tag / Machine</th><th>เครื่องจักร / งาน</th><th>Vendor</th><th>หมายเหตุ</th></tr></thead><tbody>{filtered.map(r=><tr key={str(r,'PlanID')}><td>{display(r.LastMaintenanceDate,'LastMaintenanceDate')}</td><td>{str(r,'PlanCode')}</td><td>{str(r,'TagNo')||str(r,'MachineCode')||'—'}</td><td>{str(r,'AssetName')}<br/>{str(r,'TaskDescription')}</td><td>{str(r,'VendorName')||'—'}</td><td>{str(r,'Remark')||'—'}</td></tr>)}</tbody></table></div></section>
}
