import {useEffect,useState} from 'react';
import {Save,RotateCcw,LockKeyhole,RefreshCw} from 'lucide-react';
import {roles,roleLabels,permissionResources,permissionPages,permissionMethods,immutableResources,defaultPermissions,type AppRole,type Permissions,type RolePermissions} from '../shared/permissions.mjs';
import {applyPermissions} from './access';

interface PolicyState {revision:number;roles:Permissions;roleVersions:Record<AppRole,number>;changes:{at:string;by:string;role:AppRole}[]}
const labels:Record<string,string>={overview:'ภาพรวม',reports:'รายงานและวิเคราะห์ / ส่งออก',settings:'การเชื่อมต่อระบบ',assets:'ทะเบียนเครื่องจักร','maintenance-plans':'แผน PM','work-orders':'ใบงานซ่อมบำรุง','spare-parts':'ทะเบียนอะไหล่','stock-transactions':'รับ–เบิกอะไหล่','calibration-history':'ประวัติสอบเทียบ'};
const actionLabels={GET:'ดู / เข้าถึง',POST:'เพิ่ม',PUT:'แก้ไข',DELETE:'ลบ / ยกเลิก'};
export function PermissionEditor(){
 const [state,setState]=useState<PolicyState|null>(null),[selected,setSelected]=useState<AppRole>('PLANNER'),[draft,setDraft]=useState<RolePermissions|null>(null);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false);
 const locked=selected==='ADMINISTRATOR';
 const dirty=!!state&&!!draft&&JSON.stringify(state.roles[selected])!==JSON.stringify(draft);
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/permissions');const j=await r.json();if(r.status===401)window.dispatchEvent(new Event('cmms-session-expired'));if(!r.ok)throw new Error(j.error?.message||'โหลดสิทธิ์ไม่ได้');setState(j.data);setDraft(structuredClone(j.data.roles[selected]));setConflict(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 function update(resource:string,method:typeof permissionMethods[number],checked:boolean){
  if(!draft||locked)return;const next=structuredClone(draft);next.resources[resource][method]=checked;
  if(method==='GET'&&!checked){next.resources[resource]={GET:false,POST:false,PUT:false,DELETE:false};if(['assets','work-orders','maintenance-plans','spare-parts'].includes(resource))next.pages.reports=false;}
  if(resource==='work-orders'){if(!next.resources[resource].PUT)next.history.edit=false;if(!next.resources[resource].DELETE)next.history.delete=false;}
  setDraft(next);setNotice('');
 }
 async function save(){if(!state||!draft||locked)return;setBusy(true);setError('');setNotice('');try{
  const r=await fetch('/api/permissions/'+selected,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:state.revision,permissions:draft})});const j=await r.json();if(r.status===401)window.dispatchEvent(new Event('cmms-session-expired'));if(r.status===409)setConflict(true);if(!r.ok)throw new Error(j.error?.message||'บันทึกสิทธิ์ไม่ได้');
  setState(j.data);setDraft(structuredClone(j.data.roles[selected]));applyPermissions(j.data.roles);window.dispatchEvent(new Event('cmms-permissions-updated'));setNotice('บันทึกสิทธิ์ '+roleLabels[selected]+' แล้ว ผู้ใช้บทบาทนี้ต้องเข้าสู่ระบบใหม่');setConflict(false);
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel permission-editor"><div className="panel-heading"><div><h2>กำหนดสิทธิ์ตามบทบาท</h2><p>ปรับสิทธิ์ให้ใช้กับทุกบัญชีในบทบาทที่เลือก</p></div><span className="count">{state?'เวอร์ชัน '+state.revision:'กำลังโหลด…'}</span></div>
 <div className="permission-toolbar"><label>บทบาท<select aria-label="บทบาทที่ต้องการกำหนดสิทธิ์" value={selected} disabled={busy||!state} onChange={e=>{if(dirty&&!window.confirm('มีการแก้ไขที่ยังไม่บันทึก ต้องการเปลี่ยนบทบาทหรือไม่?'))return;const r=e.target.value as AppRole;setSelected(r);setDraft(structuredClone(state!.roles[r]));setError('');setNotice('')}}>{roles.map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select></label><div className="permission-actions"><button className="button" disabled={locked||busy||!draft} onClick={()=>{setDraft(defaultPermissions()[selected]);setNotice('คืนค่าเริ่มต้นในแบบฟอร์มแล้ว กดบันทึกเพื่อนำไปใช้')}}><RotateCcw size={16}/>คืนค่าเริ่มต้น</button><button className="button primary" disabled={locked||busy||!dirty||conflict} onClick={save}><Save size={16}/>{busy?'กำลังบันทึก…':'บันทึกสิทธิ์'}</button></div></div>
 {error&&<div className="error-box" role="alert">{error}{conflict&&<button className="button small" onClick={load}><RefreshCw size={15}/>โหลดค่าล่าสุด</button>}</div>}{notice&&<p className="permission-note" role="status">{notice}</p>}
 {locked?<p className="permission-note"><LockKeyhole size={16}/>Administrator มีสิทธิ์เต็มตามที่ระบบรองรับและสงวนไว้เพื่อให้มีผู้ดูแลระบบเสมอ</p>:<p className="permission-note">{dirty?'มีการแก้ไขที่ยังไม่บันทึก · ':''}เมื่อบันทึก เซสชันเดิมของบทบาทนี้จะหมดอายุ สิทธิ์ใหม่มีผลเมื่อเข้าสู่ระบบอีกครั้ง</p>}
 {draft&&<><div className="table-scroll"><table><thead><tr><th>ฟังก์ชัน</th>{permissionMethods.map(m=><th key={m}>{actionLabels[m]}</th>)}</tr></thead><tbody>
 {permissionPages.map(page=>{const reportBlocked=page==='reports'&&!['assets','work-orders','maintenance-plans','spare-parts'].every(r=>draft.resources[r].GET);return <tr key={page}><th scope="row">{labels[page]}{reportBlocked&&<small className="permission-hint">ต้องเปิดสิทธิ์ดูเครื่องจักร ใบงาน PM และอะไหล่</small>}</th><td><input type="checkbox" aria-label={labels[page]+' ดู / เข้าถึง'} checked={draft.pages[page]} disabled={locked||busy||reportBlocked} onChange={e=>{setDraft({...draft,pages:{...draft.pages,[page]:e.target.checked}});setNotice('')}}/></td><td>—</td><td>—</td><td>—</td></tr>})}
 {permissionResources.map(resource=><tr key={resource}><th scope="row">{labels[resource]}</th>{permissionMethods.map(method=>{const unsupported=immutableResources.includes(resource)&&['PUT','DELETE'].includes(method);return <td key={method}>{unsupported?<span className="permission-unsupported" title="ระบบฐานข้อมูลไม่รองรับคำสั่งนี้"><LockKeyhole size={14}/>ไม่รองรับ</span>:<input type="checkbox" aria-label={labels[resource]+' '+actionLabels[method]} checked={selected==='PRODUCTION'&&['spare-parts','stock-transactions'].includes(resource)?false:draft.resources[resource][method]} disabled={(selected==='PRODUCTION'&&['spare-parts','stock-transactions'].includes(resource))||locked||busy||(method!=='GET'&&!draft.resources[resource].GET)} onChange={e=>update(resource,method,e.target.checked)}/>}</td>})}</tr>)}
 <tr><th scope="row">จัดการผู้ใช้และกำหนดสิทธิ์</th><td colSpan={4}><span className="permission-unsupported"><LockKeyhole size={14}/>เฉพาะ Administrator</span></td></tr>
 </tbody></table></div><div className="permission-history"><h3>ประวัติใบงานที่ปิดแล้ว</h3><p>ใช้กับใบงาน COMPLETED / CLOSED / CANCELLED เท่านั้น</p><label><input type="checkbox" aria-label="แก้ไขประวัติใบงาน" checked={draft.history.edit} disabled={locked||busy||!draft.resources['work-orders'].PUT} onChange={e=>{setDraft({...draft,history:{...draft.history,edit:e.target.checked}});setNotice('')}}/>อนุญาตแก้ไขประวัติใบงาน</label><label><input type="checkbox" aria-label="ลบหรือยกเลิกประวัติใบงาน" checked={draft.history.delete} disabled={locked||busy||!draft.resources['work-orders'].DELETE} onChange={e=>{setDraft({...draft,history:{...draft.history,delete:e.target.checked}});setNotice('')}}/>อนุญาตลบ / ยกเลิกประวัติใบงาน</label><p>การลบเป็นการยกเลิกหรือปิดใช้งานตามที่ฐานข้อมูลรองรับ รายการรับ–เบิกและสอบเทียบยังแก้ไขหรือลบไม่ได้</p><p>เมื่อให้สิทธิ์เพิ่มงาน แบบฟอร์มจะค้นหารหัสและชื่อข้อมูลอ้างอิงที่จำเป็นได้ แม้ไม่มีสิทธิ์เข้าหน้าทะเบียนนั้น</p></div></>}
 {state?.changes.length? <details className="permission-history"><summary>การเปลี่ยนสิทธิ์ล่าสุด</summary>{state.changes.slice(-5).reverse().map((c,i)=><p key={i}>{new Date(c.at).toLocaleString('th-TH')} · {roleLabels[c.role]} · {c.by}</p>)}</details>:null}
 </section>;
}
