import './purchase-summary.css';
export type PurchaseSummaryItem={code:string;total:number|null;currency:string;arrival:string};
export const purchaseSummaryPrintCss=`.purchase-summary{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:20px 0}.purchase-chart{border:1px solid #a4b5c5;border-radius:12px;padding:18px;min-width:0;break-inside:avoid}.purchase-chart h3{margin:0 0 8px}.purchase-chart p{font-size:12px;opacity:.8}.purchase-bar{margin:12px 0}.purchase-bar-label{display:flex;justify-content:space-between;gap:12px;font-size:12px;overflow-wrap:anywhere}.purchase-bar svg{display:block;width:100%;height:12px;margin-top:5px}.purchase-dates{display:flex;flex-wrap:wrap;gap:12px;margin:14px 0}.purchase-dates span{flex:1;min-width:110px;border-left:4px solid #0d9488;padding-left:12px;font-size:12px}.purchase-dates strong{display:block;font-size:17px;margin-top:5px}.purchase-warning{color:#b86b00;font-size:12px}@media(max-width:700px){.purchase-summary{grid-template-columns:1fr}}`;
const money=(n:number)=>n.toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
function Bar({label,text,value,max,color}:{label:string;text:string;value:number;max:number;color:string}){return <div className="purchase-bar"><div className="purchase-bar-label"><span>{label}</span><strong>{text}</strong></div><svg viewBox="0 0 400 12" preserveAspectRatio="none" role="img" aria-label={`${label}: ${text}`}><rect width="400" height="12" rx="6" fill="#cbd5e1" opacity=".35"/><rect width={max>0?Math.max(0,value/max*400):0} height="12" rx="6" fill={color}/></svg></div>}
export function PurchaseSummary({items,inventory={},unknownInventory=0}:{items:PurchaseSummaryItem[];inventory?:Record<string,number>;unknownInventory?:number}){
 if(!items.length)return null;
 const priced=items.filter(x=>x.total!==null&&Number.isFinite(x.total));
 const currencies=[...new Set(priced.map(x=>x.currency))].sort();
 const dates=items.map(x=>x.arrival).filter(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)).sort();
 const months:Record<string,number>={};for(const date of dates){const m=date.slice(0,7);months[m]=(months[m]||0)+1}
 const missingPrice=items.length-priced.length,missingDate=items.length-dates.length;
 return <div className="purchase-summary"><section className="purchase-chart" style={{gridColumn:"1 / -1"}}><h3>มูลค่าคงคลังก่อนและหลังรับของ</h3><p>ทั้งคลัง · ราคาต่อชิ้นปัจจุบัน × จำนวนคงเหลือ + มูลค่าที่สั่งในแผน</p>{[...new Set([...Object.keys(inventory),...currencies])].sort().map(c=>{const before=inventory[c]||0;const added=priced.filter(x=>x.currency===c).reduce((s,x)=>s+x.total!,0);const after=before+added;return <div key={c}><h4>{c} · เพิ่มตามแผน {money(added)}</h4><Bar label="ก่อนรับของ" text={`${money(before)} ${c}`} value={before} max={Math.max(before,after)} color="#64748b"/><Bar label="หลังรับของครบตามแผน" text={`${money(after)} ${c}`} value={after} max={Math.max(before,after)} color="#8b5cf6"/></div>})}<p>ประมาณการหลังรับของครบ ไม่หักการเบิกระหว่างรอของ ไม่รวมภาษีและค่าขนส่ง</p>{(unknownInventory>0||missingPrice>0)&&<p className="purchase-warning">ยอดไม่ครบ: คลัง {unknownInventory} รายการไม่มีราคา/จำนวนที่ใช้คำนวณได้ · แผน {missingPrice} รายการข้อมูลไม่ครบ</p>}</section><section className="purchase-chart"><h3>งบประมาณตามอะไหล่</h3><p>มูลค่าสูงสุด 5 รายการต่อสกุลเงิน และยอดรายการอื่น</p>{currencies.map(currency=>{const group=priced.filter(x=>x.currency===currency).sort((a,b)=>b.total!-a.total!);const top=group.slice(0,5).map(x=>({label:x.code,value:x.total!}));if(group.length>5)top.push({label:`อื่น ๆ (${group.length-5} รายการ)`,value:group.slice(5).reduce((s,x)=>s+x.total!,0)});const max=Math.max(...top.map(x=>x.value));return <div key={currency}><h4>{currency} · รวม {money(group.reduce((s,x)=>s+x.total!,0))}</h4>{top.map((x,i)=><Bar key={i} label={x.label} text={`${money(x.value)} ${currency}`} value={x.value} max={max} color="#3b82f6"/>)}</div>})}{!priced.length&&<p>ยังไม่มีราคาสำหรับคำนวณกราฟ</p>}{missingPrice>0&&<p className="purchase-warning">ไม่รวม {missingPrice} รายการที่ราคา/จำนวนยังไม่ครบ</p>}</section><section className="purchase-chart"><h3>กำหนดรับของโดยประมาณ</h3><p>จำนวนรายการอะไหล่ที่คาดว่าจะได้รับในแต่ละเดือน</p><div className="purchase-dates"><span>รับเร็วที่สุด<strong>{dates[0]||'ไม่ระบุ'}</strong></span><span>รับช้าที่สุด<strong>{dates.at(-1)||'ไม่ระบุ'}</strong></span></div>{Object.entries(months).map(([month,count])=><Bar key={month} label={month} text={`${count} รายการ`} value={count} max={Math.max(...Object.values(months))} color="#0d9488"/>)}{!dates.length&&<p>ยังไม่มีวันที่รับของสำหรับแสดงกราฟ</p>}{missingDate>0&&<p className="purchase-warning">ยังไม่ทราบวันรับ {missingDate} รายการ</p>}<p>อ้างอิงวันสั่ง + Leadtime (วันปฏิทิน)</p></section></div>
}
