import {useEffect,useState} from 'react';
import {api,num,str,value,type Row} from './api';
const numeric=(v:unknown)=>v===null||v===undefined||String(v).trim()===''||!Number.isFinite(Number(v))||Number(v)<0?null:Number(v);
const money=(n:number)=>n.toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const arrival=(date:string,lead:number|null)=>{if(!date||lead===null)return 'ไม่ระบุ';const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+Math.ceil(lead));return Number.isNaN(d.getTime())?'ไม่ระบุ':localDate(d)};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function Replenishment(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const [selected,setSelected]=useState<Record<string,string>>({}),[date,setDate]=useState(()=>localDate(new Date())),[title,setTitle]=useState('แผนสั่งอะไหล่'),[search,setSearch]=useState(''),[onlyLow,setOnlyLow]=useState(true),[page,setPage]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');Promise.all([api('spare-parts',{limit:5000},'GET',undefined,c.signal),fetch('/api/replenishment/details',{signal:c.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error?.message||'โหลดข้อมูลวางแผนไม่ได้');return j.data as Row[]})]).then(([parts,details])=>{if(parts.total!==undefined&&parts.total>parts.data.length)throw Error('ข้อมูลเกินขีดจำกัด API กรุณาตรวจสอบก่อนวางแผน');const map=new Map(details.map(r=>[str(r,'PartID'),r]));setRows(parts.data.map(r=>({...r,StandardCost:null,LeadTimeDays:null,...map.get(str(r,'PartID'))})));}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[retry]);
 const low=(r:Row)=>(value(r,'ReorderPoint')!==null&&num(r,'Quantity')<=num(r,'ReorderPoint'))||(value(r,'MinimumStock')!==null&&num(r,'Quantity')<num(r,'MinimumStock'));
 const suggested=(r:Row)=>Math.max(1,Math.ceil(Math.max(num(r,'MaximumStock'),num(r,'MinimumStock'),num(r,'ReorderPoint'))-num(r,'Quantity')));
 const list=rows.filter(r=>(!onlyLow||low(r))&&['PartCode','SAPMaterial','PartName','Brand','Department'].some(k=>str(r,k).toLowerCase().includes(search.toLowerCase())));
 const chosen=rows.filter(r=>Object.hasOwn(selected,str(r,'PartID'))).map(r=>{const qty=numeric(selected[str(r,'PartID')]),cost=numeric(value(r,'StandardCost')),lead=numeric(value(r,'LeadTimeDays'));return {r,qty,cost,lead,currency:str(r,'CurrencyCode').trim().toUpperCase()||'THB',arrival:arrival(date,lead),total:qty!==null&&cost!==null?qty*cost:null}});
 const totals=chosen.reduce<Record<string,number>>((a,x)=>{if(x.total!==null)a[x.currency]=(a[x.currency]||0)+x.total;return a},{});
 const valid=chosen.length>0&&chosen.every(x=>x.qty!==null&&x.qty>0)&&arrival(date,0)!=='ไม่ระบุ';
 function toggle(r:Row){const id=str(r,'PartID');setSelected(prev=>{const n={...prev};if(Object.hasOwn(n,id))delete n[id];else n[id]=String(suggested(r));return n})}
 const headers=['รหัสอะไหล่','SAP Material','ชื่ออะไหล่','คงเหลือ','จำนวนสั่ง','ราคาต่อชิ้น','สกุลเงิน','ราคารวม','ระยะเวลา (วัน)','คาดว่าจะได้รับ'];
 const data=chosen.map(x=>[str(x.r,'PartCode'),str(x.r,'SAPMaterial'),str(x.r,'PartName'),num(x.r,'Quantity'),x.qty??'',x.cost??'ไม่ระบุ',x.currency,x.total??'ไม่ระบุ',x.lead??'ไม่ระบุ',x.arrival]);
 const notes='ประมาณการจาก StandardCost และ LeadTimeDays นับวันปฏิทิน ไม่รวมภาษี ค่าขนส่ง และวันหยุดผู้ขาย แผนนี้ไม่ใช่ใบสั่งซื้อ และไม่เปลี่ยนยอดสต็อก';
 function csv(){const cell=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const lines=[[title],['วันสั่ง',date],headers,...data,[],...Object.entries(totals).map(([c,t])=>['รวม',c,t]),[notes]];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`replenishment-${date}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function print(){const w=window.open('','_blank');if(!w){alert('กรุณาอนุญาตป๊อปอัปเพื่อพิมพ์รายงาน');return}w.document.write(`<!doctype html><html lang="th"><meta charset="utf-8"><title>${esc(title)}</title><style>body{font:14px Tahoma,sans-serif;color:#17212c;padding:20px}table{border-collapse:collapse;width:100%;font-size:11px}td,th{border:1px solid #bbb;padding:7px;text-align:left}thead{display:table-header-group}tr{break-inside:avoid}@page{size:A4 landscape;margin:12mm}</style><h1>${esc(title)}</h1><p>วันสั่ง: ${esc(date)} | ${chosen.length} รายการ</p><table><thead><tr>${headers.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table><h3>${Object.entries(totals).map(([c,t])=>`รวม ${money(t)} ${esc(c)}`).join(' / ')}</h3><p>ไม่ระบุราคา: ${chosen.filter(x=>x.cost===null).length} | ไม่ระบุระยะเวลา: ${chosen.filter(x=>x.lead===null).length}</p><p>${notes}</p></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),350)}
 return <section className="panel report-panel replenishment"><h2>วางแผนสั่งอะไหล่</h2><p>เลือกหลายรายการเพื่อเปรียบเทียบงบประมาณและวันรับของ</p>{loading?<p role="status">กำลังโหลดข้อมูล…</p>:error?<p role="alert">{error} <button className="button" onClick={()=>setRetry(n=>n+1)}>ลองใหม่</button></p>:<>
 <div className="report-toolbar"><label>ชื่อแผน<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>วันสั่งซื้อ<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>
 <div className="category-metrics"><div>เลือกแล้ว<strong>{chosen.length} รายการ</strong></div>{Object.entries(totals).map(([c,t])=><div key={c}>ยอดประมาณการ ({c})<strong>{money(t)}</strong></div>)}<div>ไม่ระบุราคา / Leadtime<strong>{chosen.filter(x=>x.cost===null).length} / {chosen.filter(x=>x.lead===null).length}</strong></div></div>
 <h3>รายการในแผน</h3>{!chosen.length?<p>เลือกอะไหล่ด้านล่างเพื่อเริ่มวางแผน</p>:<div className="table-scroll"><table><thead><tr>{['อะไหล่','คงเหลือ','จำนวนสั่ง','ราคาต่อชิ้น','ราคารวม','ระยะเวลา (วัน)','คาดว่าจะได้รับ',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{chosen.map(x=><tr key={str(x.r,'PartID')}><td>{str(x.r,'PartCode')}<br/>{str(x.r,'PartName')}</td><td>{num(x.r,'Quantity')}</td><td><input aria-label={`จำนวนสั่ง ${str(x.r,'PartCode')}`} type="number" min="0.001" step="any" value={selected[str(x.r,'PartID')]} onChange={e=>setSelected({...selected,[str(x.r,'PartID')]:e.target.value})}/></td><td>{x.cost===null?'ไม่ระบุ':`${money(x.cost)} ${x.currency}`}</td><td>{x.total===null?'ไม่ระบุ':`${money(x.total)} ${x.currency}`}</td><td>{x.lead??'ไม่ระบุ'}</td><td>{x.arrival}</td><td><button className="button" onClick={()=>toggle(x.r)}>เอาออก</button></td></tr>)}</tbody></table></div>}
 <p>{notes}</p><p>จำนวนแนะนำเติมถึง MaximumStock หรือเกณฑ์ขั้นต่ำที่สูงสุด ถ้าไม่มีเป้าหมายจะแนะนำ 1 ชิ้น แก้จำนวนสั่งได้ ราคาที่ไม่ระบุจะไม่รวมในยอดรวม แยกยอดตามสกุลเงิน</p>
 <div className="report-toolbar"><button className="button primary" disabled={!valid} onClick={csv}>ส่งออก CSV (Excel)</button><button className="button" disabled={!valid} onClick={print}>พิมพ์ / บันทึก PDF</button></div>
 <h3>เลือกอะไหล่จากคลัง</h3><div className="report-toolbar"><input aria-label="ค้นหาอะไหล่เพื่อวางแผน" placeholder="SPM / SAP / ชื่อ / Brand / Department" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><label><input type="checkbox" checked={onlyLow} onChange={e=>{setOnlyLow(e.target.checked);setPage(0)}}/> เฉพาะที่ต้องเติมสต็อก</label><button className="button" onClick={()=>setSelected(prev=>{const n={...prev};for(const r of list)n[str(r,'PartID')]??=String(suggested(r));return n})}>เลือกทั้งหมดที่กรอง ({list.length})</button></div>
 <div className="table-scroll"><table><thead><tr><th>เลือก</th><th>รหัส / SAP</th><th>อะไหล่</th><th>คงเหลือ</th><th>จำนวนแนะนำ</th><th>ราคา / ชิ้น</th><th>ระยะเวลา (วัน)</th></tr></thead><tbody>{list.slice(page*20,page*20+20).map(r=><tr key={str(r,'PartID')}><td><input type="checkbox" aria-label={`เลือก ${str(r,'PartCode')}`} checked={Object.hasOwn(selected,str(r,'PartID'))} onChange={()=>toggle(r)}/></td><td>{str(r,'PartCode')}<br/>{str(r,'SAPMaterial')}</td><td>{str(r,'PartName')}</td><td>{num(r,'Quantity')}</td><td>{suggested(r)}</td><td>{numeric(value(r,'StandardCost'))===null?'ไม่ระบุ':`${money(num(r,'StandardCost'))} ${str(r,'CurrencyCode')||'THB'}`}</td><td>{numeric(value(r,'LeadTimeDays'))??'ไม่ระบุ'}</td></tr>)}</tbody></table></div>{!list.length&&<p>ไม่พบรายการ</p>}<div className="report-toolbar"><button className="button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>ก่อนหน้า</button><span>{page+1} / {Math.max(1,Math.ceil(list.length/20))}</span><button className="button" disabled={(page+1)*20>=list.length} onClick={()=>setPage(p=>p+1)}>ถัดไป</button></div>
 </>}</section>
}
