import type {Row} from './api';
export type ChartItem={label:string;value:number};
export function get(row:Row,key:string):unknown;
export function text(row:Row,key:string):string;
export function number(row:Row,key:string):number|null;
export function validDate(v:unknown):boolean;
export function closed(row:Row):boolean;
export function active(row:Row):boolean;
export function late(row:Row,key:string):boolean;
export function group(rows:Row[],label:(r:Row)=>string,amount?:(r:Row)=>number):ChartItem[];
export function maintenanceSummary(work:Row[],assets:Row[]):{jobs:Row[];measured:number;missing:number;totalHours:number;machines:ChartItem[];trend:ChartItem[];undated:number;meanRepairHours:number|null;durationCount:number};
export function transactionType(r:Row):string;
export type MonthlyCost={month:string;receive:number|null;issue:number|null;returned:number|null;net:number|null};
export function stockSummary(rows:Row[],parts:Row[],estimate?:boolean,fallbackCurrency?:string):{summaries:({currency:string;receive:number|null;issue:number|null;returned:number|null;net:number|null;months:MonthlyCost[];topParts:ChartItem[]})[];valued:number;estimated:number;excluded:number;undated:number;unknownType:number;inferredCurrency:number;missingCost:number;missingCurrency:number;assumedCurrency:number};
export function compliance(rows:Row[]):{eligible:number;missing:number;onTime:number;rate:number|null};
export function backlogAge(rows:Row[],now?:Date):ChartItem[];
export function monthlyCounts(rows:Row[],key:string):ChartItem[];
