import type {ChartItem} from './report-data.mjs';
const colors=['#3989e8','#ec9c36','#27b7a2','#9c7be8','#ed697d','#7c95aa'];
const fmt=(n:number)=>n.toLocaleString('th-TH',{maximumFractionDigits:1});
export function Bars({title,items,unit='รายการ',limit=8,note}:{title:string;items:ChartItem[];unit?:string;limit?:number;note?:string}){
 const shown=items.slice(0,limit),max=Math.max(1,...shown.map(x=>x.value));
 return <section className="report-chart"><h3>{title}</h3>{note&&<p className="data-note">{note}</p>}{!shown.length?<p className="chart-empty">ไม่มีข้อมูลสำหรับกราฟนี้</p>:<div className="chart-bars">{shown.map((x,i)=><div className="chart-bar-row" key={x.label}><div className="chart-bar-heading"><span>{x.label}</span><strong>{fmt(x.value)} {unit}</strong></div><div className="chart-track" aria-hidden="true"><div style={{width:`${x.value/max*100}%`,background:colors[i%colors.length]}}/></div></div>)}</div>}{items.length>limit&&<p className="data-note">แสดง {limit} อันดับแรก จาก {items.length} กลุ่ม</p>}</section>
}
export function Donut({title,items}:{title:string;items:ChartItem[]}){
 const total=items.reduce((n,x)=>n+x.value,0);let cursor=0;
 const segments=items.map((x,i)=>{const start=cursor;cursor+=total?x.value/total*100:0;return `${colors[i%colors.length]} ${start}% ${cursor}%`});
 return <section className="report-chart"><h3>{title}</h3>{!total?<p className="chart-empty">ไม่มีข้อมูลสำหรับกราฟนี้</p>:<div className="chart-donut-layout"><div className="chart-donut" aria-hidden="true" style={{background:`conic-gradient(${segments.join(',')})`}}><div><strong>{fmt(total)}</strong><span>รายการ</span></div></div><ul className="chart-legend">{items.map((x,i)=><li key={x.label}><i style={{background:colors[i%colors.length]}}/><span>{x.label}</span><strong>{fmt(x.value)} <small>({fmt(x.value/total*100)}%)</small></strong></li>)}</ul></div>}</section>
}
export function Metrics({items,decimals}:{items:[string,number|null,string][];decimals?:number}){return <div className="category-metrics">{items.map(([label,n,unit])=><div className="panel" key={label}><span>{label}</span><strong>{n===null?'—':decimals===undefined?fmt(n):n.toLocaleString('th-TH',{minimumFractionDigits:decimals,maximumFractionDigits:decimals})} <small>{unit}</small></strong></div>)}</div>}
export function Timeline({title,series,unit,note}:{title:string;series:{name:string;items:{label:string;value:number|null}[]}[];unit:string;note?:string}){
 const months=[...new Set(series.flatMap(s=>s.items.map(x=>x.label)))].sort().slice(-12);
 const max=Math.max(1,...series.flatMap(s=>s.items.filter(x=>months.includes(x.label)).map(x=>x.value||0)));
 const x=(i:number)=>65+i*(610/Math.max(1,months.length-1)),y=(v:number)=>220-v/max*175;
 return <section className="report-chart timeline-chart"><h3>{title}</h3><p className="data-note">{note||'แสดงสูงสุด 12 เดือนล่าสุดที่มีข้อมูล'} · หน่วย: {unit}</p>{!months.length?<p className="chart-empty">ไม่มีข้อมูลสำหรับกราฟนี้</p>:<><div className="timeline-scroll"><svg viewBox="0 0 740 290" role="img" aria-label={title+' ดูค่าตัวเลขในตารางใต้กราฟ'}>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1="65" x2="680" y1={y(max*f)} y2={y(max*f)} stroke="currentColor" opacity=".12"/><text x="56" y={y(max*f)+4} textAnchor="end" fill="currentColor" fontSize="11">{fmt(max*f)}</text></g>)}{months.map((m,i)=><text key={m} x={x(i)} y="245" textAnchor="end" transform={`rotate(-35 ${x(i)} 245)`} fill="currentColor" fontSize="11">{m}</text>)}{series.map((s,index)=>{const values=months.map(m=>s.items.find(x=>x.label===m)?.value??null);return <g key={s.name}>{values.map((v,i)=>v===null?null:<g key={months[i]}>{i>0&&values[i-1]!==null&&<line x1={x(i-1)} y1={y(values[i-1]!)} x2={x(i)} y2={y(v)} stroke={colors[index%colors.length]} strokeWidth="3"/>}<circle cx={x(i)} cy={y(v)} r="4" fill={colors[index%colors.length]}><title>{s.name} {months[i]}: {fmt(v)} {unit}</title></circle></g>)}</g>})}</svg></div><div className="timeline-legend">{series.map((s,i)=><span key={s.name}><i style={{background:colors[i%colors.length]}}/>{s.name}</span>)}</div><details><summary>ดูตัวเลขรายเดือน</summary><div className="table-scroll"><table><thead><tr><th>เดือน</th>{series.map(s=><th key={s.name}>{s.name} ({unit})</th>)}</tr></thead><tbody>{months.map(m=><tr key={m}><td>{m}</td>{series.map(s=>{const v=s.items.find(x=>x.label===m)?.value;return <td key={s.name}>{v==null?'—':fmt(v)}</td>})}</tr>)}</tbody></table></div></details></>}</section>
}
